/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package metroOS;

import java.awt.event.KeyEvent;

/**
 *
 * @author Vin
 */
public class Instalacion extends javax.swing.JFrame {

    /**
     * Creates new form Instalacion
     */
    
    public Instalacion() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        errorInstalacion = new javax.swing.JDialog();
        aceptarError = new javax.swing.JToggleButton();
        mensajeError = new javax.swing.JLabel();
        panelInstalacion = new javax.swing.JLayeredPane();
        labelMemoriaPpl = new javax.swing.JLabel();
        labelMemoriaSec = new javax.swing.JLabel();
        labelTamPg = new javax.swing.JLabel();
        textMemoriaPpl = new javax.swing.JTextField();
        textMemoriaSec = new javax.swing.JTextField();
        textTamPg = new javax.swing.JTextField();
        btnInstalar = new javax.swing.JButton();
        labelkBytes1 = new javax.swing.JLabel();
        labelkBytes2 = new javax.swing.JLabel();
        labelBytes = new javax.swing.JLabel();

        errorInstalacion.setTitle("Error");
        errorInstalacion.setMinimumSize(new java.awt.Dimension(475, 120));
        errorInstalacion.setType(java.awt.Window.Type.POPUP);

        aceptarError.setText("Aceptar");
        aceptarError.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                aceptarErrorActionPerformed(evt);
            }
        });

        mensajeError.setText("Error: por favor verifique que los valores introducidos sean potencia de dos.");

        javax.swing.GroupLayout errorInstalacionLayout = new javax.swing.GroupLayout(errorInstalacion.getContentPane());
        errorInstalacion.getContentPane().setLayout(errorInstalacionLayout);
        errorInstalacionLayout.setHorizontalGroup(
            errorInstalacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(errorInstalacionLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(errorInstalacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(aceptarError)
                    .addComponent(mensajeError))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        errorInstalacionLayout.setVerticalGroup(
            errorInstalacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, errorInstalacionLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(mensajeError)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(aceptarError)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Instalación MetroOS");

        panelInstalacion.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Instalación", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Monospaced", 1, 18))); // NOI18N

        labelMemoriaPpl.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        labelMemoriaPpl.setText("Introduzca el tamaño de la memoria principal:");

        labelMemoriaSec.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        labelMemoriaSec.setText("Introduzca el tamaño de la memoria secundaria:");

        labelTamPg.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        labelTamPg.setText("Introduzca el tamaño de página:");

        textMemoriaPpl.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        textMemoriaPpl.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                textMemoriaPplActionPerformed(evt);
            }
        });
        textMemoriaPpl.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyReleased(java.awt.event.KeyEvent evt)
            {
                textMemoriaPplKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt)
            {
                textMemoriaPplKeyTyped(evt);
            }
        });

        textMemoriaSec.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        textMemoriaSec.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyReleased(java.awt.event.KeyEvent evt)
            {
                textMemoriaSecKeyReleased(evt);
            }
        });

        textTamPg.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        textTamPg.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                textTamPgtextTamPgActionPerformed(evt);
            }
        });
        textTamPg.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyReleased(java.awt.event.KeyEvent evt)
            {
                textTamPgKeyReleased(evt);
            }
        });

        btnInstalar.setFont(new java.awt.Font("Monospaced", 1, 18)); // NOI18N
        btnInstalar.setText("Instalar");
        btnInstalar.setEnabled(false);
        btnInstalar.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnInstalarbtnInstalarActionPerformed(evt);
            }
        });

        labelkBytes1.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        labelkBytes1.setText("kBytes");

        labelkBytes2.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        labelkBytes2.setText("kBytes");

        labelBytes.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        labelBytes.setText("Bytes");

        panelInstalacion.setLayer(labelMemoriaPpl, javax.swing.JLayeredPane.DEFAULT_LAYER);
        panelInstalacion.setLayer(labelMemoriaSec, javax.swing.JLayeredPane.DEFAULT_LAYER);
        panelInstalacion.setLayer(labelTamPg, javax.swing.JLayeredPane.DEFAULT_LAYER);
        panelInstalacion.setLayer(textMemoriaPpl, javax.swing.JLayeredPane.DEFAULT_LAYER);
        panelInstalacion.setLayer(textMemoriaSec, javax.swing.JLayeredPane.DEFAULT_LAYER);
        panelInstalacion.setLayer(textTamPg, javax.swing.JLayeredPane.DEFAULT_LAYER);
        panelInstalacion.setLayer(btnInstalar, javax.swing.JLayeredPane.DEFAULT_LAYER);
        panelInstalacion.setLayer(labelkBytes1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        panelInstalacion.setLayer(labelkBytes2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        panelInstalacion.setLayer(labelBytes, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout panelInstalacionLayout = new javax.swing.GroupLayout(panelInstalacion);
        panelInstalacion.setLayout(panelInstalacionLayout);
        panelInstalacionLayout.setHorizontalGroup(
            panelInstalacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelInstalacionLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelInstalacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelMemoriaSec)
                    .addComponent(labelTamPg)
                    .addComponent(labelMemoriaPpl))
                .addGap(18, 18, 18)
                .addGroup(panelInstalacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelInstalacionLayout.createSequentialGroup()
                        .addComponent(textMemoriaPpl, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(labelkBytes1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(panelInstalacionLayout.createSequentialGroup()
                        .addComponent(textTamPg, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(labelBytes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(panelInstalacionLayout.createSequentialGroup()
                        .addComponent(textMemoriaSec, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(labelkBytes2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(btnInstalar, javax.swing.GroupLayout.DEFAULT_SIZE, 128, Short.MAX_VALUE))
                .addContainerGap())
        );
        panelInstalacionLayout.setVerticalGroup(
            panelInstalacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelInstalacionLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelInstalacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelMemoriaPpl)
                    .addComponent(labelkBytes1)
                    .addComponent(textMemoriaPpl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelInstalacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelMemoriaSec)
                    .addComponent(labelkBytes2)
                    .addComponent(textMemoriaSec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelInstalacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelTamPg)
                    .addComponent(labelBytes)
                    .addComponent(textTamPg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnInstalar)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelInstalacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelInstalacion)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void textTamPgtextTamPgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textTamPgtextTamPgActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textTamPgtextTamPgActionPerformed

    private void btnInstalarbtnInstalarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInstalarbtnInstalarActionPerformed
        int sizeP = Integer.parseInt(textMemoriaPpl.getText());
        int sizeS = Integer.parseInt(textMemoriaSec.getText());
        int sizePage = Integer.parseInt(textTamPg.getText());
        
        if (!validadorPotencia2(Integer.parseInt(textMemoriaPpl.getText())) || !validadorPotencia2(Integer.parseInt(textMemoriaSec.getText())) ||
                !validadorPotencia2(Integer.parseInt(textTamPg.getText())))
        {
            textMemoriaPpl.setText("");
            textMemoriaSec.setText("");
            textTamPg.setText("");
            btnInstalar.setEnabled(false);
            mensajeError.setText("Error: por favor verifique que los valores introducidos sean potencia de dos.");
            errorInstalacion.setLocationRelativeTo(null);
            errorInstalacion.setVisible(true);
        }
        else
        {
            panelInstalacion.setVisible(false);
            Interfaz UI = new Interfaz(sizeP*1024, sizeS*1024, sizePage);
            UI.setLocationRelativeTo(null);
            UI.setVisible(true);
        }
    }//GEN-LAST:event_btnInstalarbtnInstalarActionPerformed

    private void aceptarErrorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aceptarErrorActionPerformed
        // TODO add your handling code here:
        errorInstalacion.setVisible(false);

    }//GEN-LAST:event_aceptarErrorActionPerformed

    private void textMemoriaPplKeyTyped(java.awt.event.KeyEvent evt)//GEN-FIRST:event_textMemoriaPplKeyTyped
    {//GEN-HEADEREND:event_textMemoriaPplKeyTyped
        char c=evt.getKeyChar();
        if (!((Character.isDigit(c)) || (c == KeyEvent.VK_BACK_SPACE) || (c == KeyEvent.VK_DELETE))) 
        {
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_textMemoriaPplKeyTyped

    private void textMemoriaPplKeyReleased(java.awt.event.KeyEvent evt)//GEN-FIRST:event_textMemoriaPplKeyReleased
    {//GEN-HEADEREND:event_textMemoriaPplKeyReleased
        if (textMemoriaPpl.getText().length() > 0 && textMemoriaSec.getText().length() > 0 && textTamPg.getText().length() > 0)
        {
            btnInstalar.setEnabled(true);
        }
        else
        {
            btnInstalar.setEnabled(false);
        }
    }//GEN-LAST:event_textMemoriaPplKeyReleased

    private void textMemoriaSecKeyReleased(java.awt.event.KeyEvent evt)//GEN-FIRST:event_textMemoriaSecKeyReleased
    {//GEN-HEADEREND:event_textMemoriaSecKeyReleased
        if (textMemoriaPpl.getText().length() > 0 && textMemoriaSec.getText().length() > 0 && textTamPg.getText().length() > 0)
        {
            btnInstalar.setEnabled(true);
        }
        else
        {
            btnInstalar.setEnabled(false);
        }
    }//GEN-LAST:event_textMemoriaSecKeyReleased

    private void textTamPgKeyReleased(java.awt.event.KeyEvent evt)//GEN-FIRST:event_textTamPgKeyReleased
    {//GEN-HEADEREND:event_textTamPgKeyReleased
        if (textMemoriaPpl.getText().length() > 0 && textMemoriaSec.getText().length() > 0 && textTamPg.getText().length() > 0)
        {
            btnInstalar.setEnabled(true);
        }
        else
        {
            btnInstalar.setEnabled(false);
        }
    }//GEN-LAST:event_textTamPgKeyReleased

    private void textMemoriaPplActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_textMemoriaPplActionPerformed
    {//GEN-HEADEREND:event_textMemoriaPplActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textMemoriaPplActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Instalacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Instalacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Instalacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Instalacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Instalacion().setVisible(true);
            }
        });
    }
    
    public boolean validadorPotencia2 (int decimal)
    {
        return (decimal > 0) && ((decimal & (decimal - 1)) == 0);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton aceptarError;
    private javax.swing.JButton btnInstalar;
    private javax.swing.JDialog errorInstalacion;
    private javax.swing.JLabel labelBytes;
    private javax.swing.JLabel labelMemoriaPpl;
    private javax.swing.JLabel labelMemoriaSec;
    private javax.swing.JLabel labelTamPg;
    private javax.swing.JLabel labelkBytes1;
    private javax.swing.JLabel labelkBytes2;
    private javax.swing.JLabel mensajeError;
    private javax.swing.JLayeredPane panelInstalacion;
    private javax.swing.JTextField textMemoriaPpl;
    private javax.swing.JTextField textMemoriaSec;
    private javax.swing.JTextField textTamPg;
    // End of variables declaration//GEN-END:variables
}
